import type {
  ActiveWorkoutDraft,
  EquipmentProfile,
  ExerciseTemplate,
  WorkoutCategory,
  WorkoutTemplate,
} from "@/lib/brgym/types";

const timestamp = "2026-06-03T00:00:00.000Z";

export const STRUGGLE_LABELS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: "Too easy",
  2: "Solid, had more reps",
  3: "Challenging but clean",
  4: "Very hard",
  5: "Failed / form broke down",
};

export const BAND_ASSISTANCE_OPTIONS = [
  "5-10 lb",
  "15-30 lb",
  "30-60 lb",
  "60-100 lb",
  "100-125 lb",
] as const;

function createExercise(
  id: string,
  name: string,
  movementPattern: string,
  exerciseType: ExerciseTemplate["exerciseType"],
  equipment: ExerciseTemplate["equipment"],
  notes = "",
  sensitivityFlags: ExerciseTemplate["sensitivityFlags"] = {
    knee: false,
    lowerBack: false,
    shoulder: false,
  },
  targetSets = 3,
  repMin = 8,
  repMax = 12,
  progressionIncrement = 5,
): ExerciseTemplate {
  return {
    id,
    name,
    movementPattern,
    targetSets,
    repMin,
    repMax,
    equipment,
    progressionIncrement,
    notes,
    sensitivityFlags,
    exerciseType,
  };
}

export const EXERCISE_LIBRARY: Record<string, ExerciseTemplate> = {
  "Barbell bench press": createExercise(
    "barbell-bench-press",
    "Barbell bench press",
    "horizontal press",
    "barbell",
    ["barbell", "squat rack", "adjustable bench"],
    "Classic press. Keep shoulders packed on the bench.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    12,
    5,
  ),
  "Dumbbell bench press": createExercise(
    "dumbbell-bench-press",
    "Dumbbell bench press",
    "horizontal press",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "flat bench", "adjustable bench"],
    "Neutral grip is fine if shoulders feel better that way.",
    { knee: false, lowerBack: false, shoulder: true },
  ),
  "Dumbbell incline bench press": createExercise(
    "dumbbell-incline-bench-press",
    "Dumbbell incline bench press",
    "incline press",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench"],
    "A 20-30 degree incline usually works well.",
    { knee: false, lowerBack: false, shoulder: true },
  ),
  "Cable tricep pulldown": createExercise(
    "cable-tricep-pulldown",
    "Cable tricep pulldown",
    "tricep extension",
    "cable",
    ["cable", "functional trainer"],
    "Keep elbows pinned and finish with control.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    10,
    12,
    5,
  ),
  "Dumbbell tricep extension": createExercise(
    "dumbbell-tricep-extension",
    "Dumbbell tricep extension",
    "tricep extension",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench"],
    "Use a modest range if shoulders feel cranky.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    12,
    2.5,
  ),
  "Pull-up / assisted pull-up": {
    ...createExercise(
      "pull-up-assisted-pull-up",
      "Pull-up / assisted pull-up",
      "vertical pull",
      "bodyweight",
      ["pull-up bar", "bands", "bodyweight"],
      "Use a band if needed and keep the movement smooth.",
      { knee: false, lowerBack: false, shoulder: false },
      3,
      6,
      12,
      0,
    ),
    defaultBandAssistance: "30-60 lb",
  },
  "Dumbbell bent-over row": createExercise(
    "dumbbell-bent-over-row",
    "Dumbbell bent-over row",
    "horizontal pull",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench"],
    "Brace hard and avoid yanking with the low back.",
    { knee: false, lowerBack: true, shoulder: false },
  ),
  "Cable lat pulldown": createExercise(
    "cable-lat-pulldown",
    "Cable lat pulldown",
    "vertical pull",
    "cable",
    ["cable", "functional trainer"],
    "Pull elbows to ribs and avoid shrugging up.",
  ),
  "Dumbbell curl": createExercise(
    "dumbbell-curl",
    "Dumbbell curl",
    "elbow flexion",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Controlled lowers beat swinging.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    8,
    12,
    2.5,
  ),
  "Dumbbell hammer curl": createExercise(
    "dumbbell-hammer-curl",
    "Dumbbell hammer curl",
    "elbow flexion",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Neutral grip. Keep upper arm quiet.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    8,
    12,
    2.5,
  ),
  "Hex bar deadlift": createExercise(
    "hex-bar-deadlift",
    "Hex bar deadlift",
    "hinge",
    "hexbar",
    ["hex bar"],
    "Drive through the floor and keep ribs stacked.",
    { knee: false, lowerBack: true, shoulder: false },
    3,
    6,
    10,
    10,
  ),
  "Dumbbell goblet squat": createExercise(
    "dumbbell-goblet-squat",
    "Dumbbell goblet squat",
    "squat",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Sit between the hips and keep torso tall.",
    { knee: true, lowerBack: false, shoulder: false },
  ),
  "Dumbbell Bulgarian split squat": createExercise(
    "dumbbell-bulgarian-split-squat",
    "Dumbbell Bulgarian split squat",
    "lunge",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench", "flat bench"],
    "Shorten ROM if knees are cranky today.",
    { knee: true, lowerBack: false, shoulder: false },
  ),
  "Dumbbell Romanian deadlift": createExercise(
    "dumbbell-romanian-deadlift",
    "Dumbbell Romanian deadlift",
    "hinge",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Soft knees, reach hips back, stop before low-back compensation.",
    { knee: false, lowerBack: true, shoulder: false },
  ),
  "Dumbbell shoulder press": createExercise(
    "dumbbell-shoulder-press",
    "Dumbbell shoulder press",
    "overhead press",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench"],
    "Neutral grip or low incline can be the safer option.",
    { knee: false, lowerBack: false, shoulder: true },
  ),
  "Dumbbell lateral raise": createExercise(
    "dumbbell-lateral-raise",
    "Dumbbell lateral raise",
    "shoulder abduction",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Keep the swing low and the tension high.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    10,
    15,
    2.5,
  ),
  "Face pulls": createExercise(
    "face-pulls",
    "Face pulls",
    "rear delt / posture",
    "cable",
    ["cable", "functional trainer", "bands"],
    "Pull high with elbows wide and finish toward the face.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    12,
    15,
    5,
  ),
  "Rear delt fly": createExercise(
    "rear-delt-fly",
    "Rear delt fly",
    "rear delt / posture",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench"],
    "Support chest if you want less low-back fatigue.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    12,
    15,
    2.5,
  ),
  "Neck and posture stability": createExercise(
    "neck-and-posture-stability",
    "Neck and posture stability",
    "posture stability",
    "bodyweight",
    ["bodyweight"],
    "Keep it light and controlled. This is optional support work.",
    { knee: false, lowerBack: false, shoulder: false },
    2,
    10,
    15,
    0,
  ),
  "Push-ups": createExercise(
    "push-ups",
    "Push-ups",
    "horizontal press",
    "bodyweight",
    ["bodyweight"],
    "Elevate hands if needed to keep reps clean.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    15,
    0,
  ),
  "Flat dumbbell bench press": createExercise(
    "flat-dumbbell-bench-press",
    "Flat dumbbell bench press",
    "horizontal press",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "flat bench", "adjustable bench"],
    "A simple hotel-gym swap for incline work.",
    { knee: false, lowerBack: false, shoulder: true },
  ),
  "Push-up variation": createExercise(
    "push-up-variation",
    "Push-up variation",
    "horizontal press",
    "bodyweight",
    ["bodyweight"],
    "Hands elevated, tempo, or deficit depending on setup.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    15,
    0,
  ),
  "Dumbbell skull crusher": createExercise(
    "dumbbell-skull-crusher",
    "Dumbbell skull crusher",
    "tricep extension",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "flat bench", "adjustable bench"],
    "Good cable-free tricep option.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    12,
    2.5,
  ),
  "Dumbbell overhead extension": createExercise(
    "dumbbell-overhead-extension",
    "Dumbbell overhead extension",
    "tricep extension",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Conservative if shoulders are irritated.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    12,
    2.5,
  ),
  "Band pressdown": createExercise(
    "band-pressdown",
    "Band pressdown",
    "tricep extension",
    "banded",
    ["bands"],
    "Quick swap when cables are missing.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    12,
    15,
    0,
  ),
  "Band lat pulldown": createExercise(
    "band-lat-pulldown",
    "Band lat pulldown",
    "vertical pull",
    "banded",
    ["bands"],
    "Anchor high and pull elbows toward back pockets.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    10,
    15,
    0,
  ),
  "Dumbbell pullover": createExercise(
    "dumbbell-pullover",
    "Dumbbell pullover",
    "vertical pull",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "flat bench", "adjustable bench"],
    "Not a perfect lat pulldown clone, but usable in a pinch.",
    { knee: false, lowerBack: false, shoulder: true },
    3,
    8,
    12,
    2.5,
  ),
  "One-arm dumbbell row": createExercise(
    "one-arm-dumbbell-row",
    "One-arm dumbbell row",
    "horizontal pull",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench", "flat bench"],
    "Support one hand to keep it back-friendly.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    8,
    12,
    2.5,
  ),
  "Dumbbell deadlift": createExercise(
    "dumbbell-deadlift",
    "Dumbbell deadlift",
    "hinge",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells"],
    "Neutral grip, modest depth, clean hinge.",
    { knee: false, lowerBack: true, shoulder: false },
  ),
  "Split squat": createExercise(
    "split-squat",
    "Split squat",
    "lunge",
    "bodyweight",
    ["bodyweight"],
    "Bodyweight or light load if knees feel sensitive.",
    { knee: true, lowerBack: false, shoulder: false },
    3,
    8,
    12,
    0,
  ),
  "Tempo bodyweight squat": createExercise(
    "tempo-bodyweight-squat",
    "Tempo bodyweight squat",
    "squat",
    "bodyweight",
    ["bodyweight"],
    "Use a controlled eccentric and a pause at the bottom.",
    { knee: true, lowerBack: false, shoulder: false },
    3,
    10,
    15,
    0,
  ),
  "Band face pull": createExercise(
    "band-face-pull",
    "Band face pull",
    "rear delt / posture",
    "banded",
    ["bands"],
    "Easy swap when cables are unavailable.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    12,
    15,
    0,
  ),
  "Incline-supported rear delt work": createExercise(
    "incline-supported-rear-delt-work",
    "Incline-supported rear delt work",
    "rear delt / posture",
    "dumbbell",
    ["dumbbells", "adjustable dumbbells", "adjustable bench"],
    "A solid shoulder-friendly swap for pressing volume.",
    { knee: false, lowerBack: false, shoulder: false },
    3,
    12,
    15,
    2.5,
  ),
};

function getExercises(names: string[]): ExerciseTemplate[] {
  return names.map((name) => {
    const found = EXERCISE_LIBRARY[name];
    if (!found) {
      throw new Error(`Missing exercise library entry for ${name}`);
    }
    return found;
  });
}

function createTemplate(id: string, name: string, category: WorkoutCategory, exerciseNames: string[]): WorkoutTemplate {
  return {
    id,
    name,
    category,
    exercises: getExercises(exerciseNames).map((exercise) => ({ ...exercise })),
    createdAt: timestamp,
    updatedAt: timestamp,
    isDefault: true,
  };
}

export const DEFAULT_TEMPLATES: WorkoutTemplate[] = [
  createTemplate("push-default", "Push", "Push", [
    "Barbell bench press",
    "Dumbbell incline bench press",
    "Cable tricep pulldown",
    "Dumbbell tricep extension",
  ]),
  createTemplate("pull-default", "Pull", "Pull", [
    "Pull-up / assisted pull-up",
    "Dumbbell bent-over row",
    "Cable lat pulldown",
    "Dumbbell curl",
    "Dumbbell hammer curl",
  ]),
  createTemplate("legs-default", "Legs / Lower Back", "Legs / Lower Back", [
    "Hex bar deadlift",
    "Dumbbell goblet squat",
    "Dumbbell Bulgarian split squat",
    "Dumbbell Romanian deadlift",
  ]),
  createTemplate("shoulders-default", "Shoulders / Posture", "Shoulders / Posture", [
    "Dumbbell shoulder press",
    "Dumbbell lateral raise",
    "Face pulls",
    "Rear delt fly",
    "Neck and posture stability",
  ]),
  createTemplate("full-body-default", "Full Body", "Full Body", [
    "Dumbbell goblet squat",
    "Dumbbell bench press",
    "One-arm dumbbell row",
    "Dumbbell Romanian deadlift",
  ]),
  {
    ...createTemplate("push-day-save-1", "Push Day Save 1", "Push", [
      "Push-ups",
      "Dumbbell bench press",
      "Cable tricep pulldown",
    ]),
    isDefault: false,
  },
];

export const DEFAULT_EQUIPMENT_PROFILES: EquipmentProfile[] = [
  {
    id: "apartment-gym",
    name: "Apartment Gym",
    description: "Fullest setup with dumbbells, barbell, cable access, and a hex bar.",
    supportedEquipment: [
      "dumbbells",
      "cable",
      "functional trainer",
      "squat rack",
      "adjustable bench",
      "barbell",
      "pull-up bar",
      "hex bar",
      "bodyweight",
      "bands",
    ],
    primaryUnit: "lb",
    dumbbellWeights: [5, 10, 12.5, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70],
    cableWeights: Array.from({ length: 14 }, (_, index) => (index + 1) * 10),
  },
  {
    id: "hotel-gym",
    name: "Hotel Gym",
    description: "Simple dumbbell + bench travel setup.",
    supportedEquipment: ["dumbbells", "flat bench", "bodyweight"],
    primaryUnit: "lb",
    dumbbellWeights: [5, 10, 15, 20, 25, 30, 35, 40],
  },
  {
    id: "eh-gym",
    name: "EH Gym",
    description: "KG-first adjustable dumbbells with bench and ropes.",
    supportedEquipment: ["adjustable bench", "adjustable dumbbells", "battle ropes", "bodyweight"],
    primaryUnit: "kg",
    dumbbellWeights: [2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25],
  },
];

export const DEFAULT_SETTINGS = {
  defaultRestSeconds: 120,
  timerSoundMuted: false,
  activeEquipmentProfileId: "apartment-gym",
  preferredTheme: "dark" as const,
};

export const CATEGORY_SEQUENCE: WorkoutCategory[] = [
  "Push",
  "Pull",
  "Legs / Lower Back",
  "Shoulders / Posture",
];

export const EXERCISE_SUBSTITUTIONS: Record<string, string[]> = {
  "Cable tricep pulldown": ["Dumbbell skull crusher", "Dumbbell overhead extension", "Band pressdown"],
  "Cable lat pulldown": ["Pull-up / assisted pull-up", "Band lat pulldown", "Dumbbell pullover", "One-arm dumbbell row"],
  "Barbell bench press": ["Dumbbell bench press", "Push-ups"],
  "Dumbbell incline bench press": ["Flat dumbbell bench press", "Push-up variation"],
  "Hex bar deadlift": ["Dumbbell Romanian deadlift", "Dumbbell deadlift"],
  "Dumbbell goblet squat": ["Split squat", "Tempo bodyweight squat"],
  "Face pulls": ["Band face pull", "Rear delt fly"],
  "Dumbbell shoulder press": [
    "Dumbbell lateral raise",
    "Incline-supported rear delt work",
    "Push-up variation",
  ],
};

export function createEmptyWorkout(): ActiveWorkoutDraft | null {
  return null;
}
