// Generated by scripts/build_advanced_usage_validation.py.
export const advancedUsageValidation = {
  "generatedAt": "2026-08-13",
  "trainSeasons": [
    2022,
    2023,
    2024
  ],
  "holdoutSeason": 2025,
  "reports": [
    {
      "position": "RB",
      "trainSamples": 200,
      "holdoutSamples": 63,
      "holdoutSeason": 2025,
      "baselineMae": 2.777,
      "advancedMae": 2.651,
      "maeImprovement": 0.0453,
      "activationEligible": true
    },
    {
      "position": "WR",
      "trainSamples": 336,
      "holdoutSamples": 109,
      "holdoutSeason": 2025,
      "baselineMae": 2.508,
      "advancedMae": 2.348,
      "maeImprovement": 0.0635,
      "activationEligible": true
    },
    {
      "position": "TE",
      "trainSamples": 173,
      "holdoutSamples": 62,
      "holdoutSeason": 2025,
      "baselineMae": 2.17,
      "advancedMae": 2.079,
      "maeImprovement": 0.0419,
      "activationEligible": true
    }
  ]
} as const;
