// Generated by scripts/build_nfl_milestone_snapshot.py.
export const nflMilestones2025 = {
  "00-0026158": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0026498": {
    "passing300Games": 6,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0029263": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0029604": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0030061": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0030279": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0030565": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0031236": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0031381": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0031408": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0031503": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0031588": {
    "passing300Games": 0,
    "receiving100Games": 5,
    "rushing100Games": 0
  },
  "00-0032764": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 8
  },
  "00-0032775": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0032950": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0033040": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0033077": {
    "passing300Games": 6,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0033090": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0033106": {
    "passing300Games": 6,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0033119": {
    "passing300Games": 4,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0033280": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 4
  },
  "00-0033288": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0033307": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0033555": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0033873": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0033921": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0033923": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0034348": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0034351": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0034775": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0034837": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0034844": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 4
  },
  "00-0034855": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0034857": {
    "passing300Games": 3,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0034869": {
    "passing300Games": 3,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0035261": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 3
  },
  "00-0035640": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0035645": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0035676": {
    "passing300Games": 0,
    "receiving100Games": 5,
    "rushing100Games": 0
  },
  "00-0035685": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0035710": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036139": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 3
  },
  "00-0036158": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0036212": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036223": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 5
  },
  "00-0036252": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0036264": {
    "passing300Games": 3,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036275": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 3
  },
  "00-0036322": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0036355": {
    "passing300Games": 4,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036358": {
    "passing300Games": 0,
    "receiving100Games": 6,
    "rushing100Games": 0
  },
  "00-0036389": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036410": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0036442": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036554": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0036613": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0036875": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0036894": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0036900": {
    "passing300Games": 0,
    "receiving100Games": 7,
    "rushing100Games": 0
  },
  "00-0036912": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0036963": {
    "passing300Games": 0,
    "receiving100Games": 5,
    "rushing100Games": 0
  },
  "00-0036970": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0036971": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036972": {
    "passing300Games": 3,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0036973": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0036997": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0037228": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0037238": {
    "passing300Games": 0,
    "receiving100Games": 5,
    "rushing100Games": 0
  },
  "00-0037239": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0037240": {
    "passing300Games": 0,
    "receiving100Games": 4,
    "rushing100Games": 0
  },
  "00-0037247": {
    "passing300Games": 0,
    "receiving100Games": 5,
    "rushing100Games": 0
  },
  "00-0037248": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 10
  },
  "00-0037261": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0037291": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0037525": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0037545": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0037563": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0037664": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0037744": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0037816": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0037834": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0037840": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0038117": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0038120": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 4
  },
  "00-0038124": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0038134": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 4
  },
  "00-0038542": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 5
  },
  "00-0038543": {
    "passing300Games": 0,
    "receiving100Games": 10,
    "rushing100Games": 0
  },
  "00-0038544": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0038555": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0038559": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0038563": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0038597": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 3
  },
  "00-0038606": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0038608": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0038621": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0038797": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0038933": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0038951": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0038994": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0038996": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0039040": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 4
  },
  "00-0039064": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0039067": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039075": {
    "passing300Games": 0,
    "receiving100Games": 8,
    "rushing100Games": 0
  },
  "00-0039139": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 3
  },
  "00-0039150": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0039163": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0039165": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0039337": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039338": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0039361": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039384": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0039391": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 3
  },
  "00-0039405": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0039410": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0039491": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039732": {
    "passing300Games": 4,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0039738": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0039851": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0039855": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039874": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0039875": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0039890": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039901": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0039915": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0039916": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0039917": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0039918": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0039919": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0040122": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0040124": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0040126": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0040129": {
    "passing300Games": 0,
    "receiving100Games": 3,
    "rushing100Games": 0
  },
  "00-0040189": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0040236": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0040242": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0040583": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0040663": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0040666": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  },
  "00-0040668": {
    "passing300Games": 1,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0040718": {
    "passing300Games": 0,
    "receiving100Games": 1,
    "rushing100Games": 0
  },
  "00-0040734": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 2
  },
  "00-0040735": {
    "passing300Games": 0,
    "receiving100Games": 2,
    "rushing100Games": 0
  },
  "00-0040743": {
    "passing300Games": 2,
    "receiving100Games": 0,
    "rushing100Games": 0
  },
  "00-0040784": {
    "passing300Games": 0,
    "receiving100Games": 0,
    "rushing100Games": 1
  }
} as const;
