// Generated by scripts/build_rookie_wr_validation.py.
// Leakage-safe expanding-window validation; do not hand-edit.
export const rookieWrValidation = {
  "ablations": {
    "full": {
      "balancedAccuracy": 0.573,
      "brier": 0.086,
      "f1": 0.25,
      "mae": 2.8266,
      "pairwiseAccuracy": 0.7343,
      "positives": 24,
      "prAuc": 0.4281,
      "precision": 0.5,
      "recall": 0.1667,
      "spearman": 0.5824
    },
    "market": {
      "balancedAccuracy": 0.5599,
      "brier": 0.0875,
      "f1": 0.2143,
      "mae": 2.8427,
      "pairwiseAccuracy": 0.7471,
      "positives": 24,
      "prAuc": 0.4227,
      "precision": 0.75,
      "recall": 0.125,
      "spearman": 0.5648
    },
    "opportunity": {
      "balancedAccuracy": 0.573,
      "brier": 0.0865,
      "f1": 0.25,
      "mae": 2.7721,
      "pairwiseAccuracy": 0.7548,
      "positives": 24,
      "prAuc": 0.4113,
      "precision": 0.5,
      "recall": 0.1667,
      "spearman": 0.6169
    },
    "selected": {
      "balancedAccuracy": 0.5756,
      "brier": 0.0872,
      "f1": 0.2581,
      "mae": 2.8723,
      "pairwiseAccuracy": 0.7392,
      "positives": 24,
      "prAuc": 0.4118,
      "precision": 0.5714,
      "recall": 0.1667,
      "spearman": 0.5532
    },
    "targetQuality": {
      "balancedAccuracy": 0.599,
      "brier": 0.0859,
      "f1": 0.3226,
      "mae": 2.924,
      "pairwiseAccuracy": 0.7237,
      "positives": 24,
      "prAuc": 0.4393,
      "precision": 0.7143,
      "recall": 0.2083,
      "spearman": 0.5177
    }
  },
  "activationEligible": false,
  "blockers": [
    "MAE improvement -1.0% is below the 2.0% threshold.",
    "Spearman lift -0.012 is below the 0.030 threshold.",
    "Only 0 of 7 holdouts improved MAE; at least 4 are required.",
    "Direct-ADP MAE regressed 2.2%; opportunity adjustments may only be eligible for proxy-ADP players."
  ],
  "breakoutActivationEligible": false,
  "breakoutBlockers": [
    "WR3 precision-recall AUC lift -0.011 is below the 0.030 breakout threshold."
  ],
  "coverage": {
    "allRows": 305,
    "depthChartRows": 304,
    "directAdpRows": 69,
    "topThreePathRows": 35
  },
  "folds": [
    {
      "holdoutSamples": 30,
      "marketMae": 3.7147,
      "marketSpearman": 0.3879,
      "researchMae": 3.7147,
      "researchSpearman": 0.3879,
      "ridgePenalty": 5.0,
      "season": 2019,
      "selectedLane": "market",
      "selectionDiagnostics": {
        "fullMae": 3.381571817879807,
        "fullSpearman": 0.390076675545066,
        "marketMae": 3.1505802895883472,
        "marketSpearman": 0.499202855693089,
        "opportunityMae": 3.0844711471163913,
        "opportunitySpearman": 0.3864325360568456,
        "targetQualityMae": 3.2888081064290726,
        "targetQualitySpearman": 0.4235579207056042
      },
      "trainSamples": 88
    },
    {
      "holdoutSamples": 34,
      "marketMae": 3.1368,
      "marketSpearman": 0.7152,
      "researchMae": 3.1368,
      "researchSpearman": 0.7152,
      "ridgePenalty": 20.0,
      "season": 2020,
      "selectedLane": "market",
      "selectionDiagnostics": {
        "fullMae": 3.6930992289988627,
        "fullSpearman": 0.2874031670128577,
        "marketMae": 3.6981940118396914,
        "marketSpearman": 0.3879322639342999,
        "opportunityMae": 3.632808326238063,
        "opportunitySpearman": 0.5277605091694602,
        "targetQualityMae": 3.73357449396207,
        "targetQualitySpearman": 0.26555249954407567
      },
      "trainSamples": 118
    },
    {
      "holdoutSamples": 23,
      "marketMae": 2.8666,
      "marketSpearman": 0.73,
      "researchMae": 3.0497,
      "researchSpearman": 0.7191,
      "ridgePenalty": 1.0,
      "season": 2021,
      "selectedLane": "full",
      "selectionDiagnostics": {
        "fullMae": 2.9458638677944866,
        "fullSpearman": 0.7619268281777334,
        "marketMae": 3.131748392102725,
        "marketSpearman": 0.7152257077276205,
        "opportunityMae": 3.015672408840022,
        "opportunitySpearman": 0.7662081749947064,
        "targetQualityMae": 3.0850296223884803,
        "targetQualitySpearman": 0.6799696176813927
      },
      "trainSamples": 152
    },
    {
      "holdoutSamples": 24,
      "marketMae": 2.2435,
      "marketSpearman": 0.7095,
      "researchMae": 2.2435,
      "researchSpearman": 0.7095,
      "ridgePenalty": 1.0,
      "season": 2022,
      "selectedLane": "market",
      "selectionDiagnostics": {
        "fullMae": 2.849730960959361,
        "fullSpearman": 0.7497530868425901,
        "marketMae": 2.8087427165693066,
        "marketSpearman": 0.72997068349582,
        "opportunityMae": 2.770170670628318,
        "opportunitySpearman": 0.72997068349582,
        "targetQualityMae": 2.871222778659504,
        "targetQualitySpearman": 0.6488628297740623
      },
      "trainSamples": 175
    },
    {
      "holdoutSamples": 35,
      "marketMae": 3.0692,
      "marketSpearman": 0.6441,
      "researchMae": 3.0692,
      "researchSpearman": 0.6441,
      "ridgePenalty": 50.0,
      "season": 2023,
      "selectedLane": "market",
      "selectionDiagnostics": {
        "fullMae": 2.1234664854108245,
        "fullSpearman": 0.7249402215296771,
        "marketMae": 2.211273495676703,
        "marketSpearman": 0.7094850685306161,
        "opportunityMae": 2.1318204303241592,
        "opportunitySpearman": 0.7114590296476013,
        "targetQualityMae": 2.131847067886427,
        "targetQualitySpearman": 0.7171124326949234
      },
      "trainSamples": 199
    },
    {
      "holdoutSamples": 34,
      "marketMae": 2.824,
      "marketSpearman": 0.728,
      "researchMae": 2.8886,
      "researchSpearman": 0.668,
      "ridgePenalty": 50.0,
      "season": 2024,
      "selectedLane": "opportunity",
      "selectionDiagnostics": {
        "fullMae": 3.067997698294905,
        "fullSpearman": 0.6690944760437929,
        "marketMae": 3.0691505708220252,
        "marketSpearman": 0.6440624919348562,
        "opportunityMae": 2.9733721759123304,
        "opportunitySpearman": 0.6915050090492371,
        "targetQualityMae": 3.178978297006437,
        "targetQualitySpearman": 0.6419217047746918
      },
      "trainSamples": 234
    },
    {
      "holdoutSamples": 37,
      "marketMae": 2.0424,
      "marketSpearman": 0.6855,
      "researchMae": 2.0424,
      "researchSpearman": 0.6855,
      "ridgePenalty": 5.0,
      "season": 2025,
      "selectedLane": "market",
      "selectionDiagnostics": {
        "fullMae": 2.9823342247410403,
        "fullSpearman": 0.6504698620863287,
        "marketMae": 2.821009076552905,
        "marketSpearman": 0.7282890855177186,
        "opportunityMae": 2.888621019046507,
        "opportunitySpearman": 0.6680418691664153,
        "targetQualityMae": 2.907481130117482,
        "targetQualitySpearman": 0.6966154806792514
      },
      "trainSamples": 268
    }
  ],
  "generatedAt": "2026-08-14T16:52:32.317004+00:00",
  "holdoutSeasons": [
    2019,
    2020,
    2021,
    2022,
    2023,
    2024,
    2025
  ],
  "lane": "rookie-wr",
  "maeImprovement": -0.0104,
  "marketMae": 2.843,
  "marketWr3Accuracy": 0.5599,
  "medianActivationEligible": false,
  "methodology": [
    "Every outer holdout chooses its lane and ridge strength using only the latest season inside its earlier training window.",
    "The baseline and challenger separately predict targets/game, catch rate, yards/target, TD/target, and rushing points/game.",
    "Opportunity predicts market residuals from opening depth-chart path, depth order, college workload, and breakout result.",
    "Direct-ADP and draft-proxy rows are reported separately so a weak fallback cannot masquerade as a market edge.",
    "Median activation requires MAE, rank-correlation, and season-stability improvement; WR3 PR-AUC is a separate breakout gate.",
    "The serialized opportunity model changes target volume only and is capped at plus or minus eight percent."
  ],
  "metrics": {
    "full": {
      "balancedAccuracy": 0.573,
      "brier": 0.086,
      "f1": 0.25,
      "mae": 2.8266,
      "pairwiseAccuracy": 0.7343,
      "positives": 24,
      "prAuc": 0.4281,
      "precision": 0.5,
      "recall": 0.1667,
      "spearman": 0.5824
    },
    "market": {
      "balancedAccuracy": 0.5599,
      "brier": 0.0875,
      "f1": 0.2143,
      "mae": 2.8427,
      "pairwiseAccuracy": 0.7471,
      "positives": 24,
      "prAuc": 0.4227,
      "precision": 0.75,
      "recall": 0.125,
      "spearman": 0.5648
    },
    "opportunity": {
      "balancedAccuracy": 0.573,
      "brier": 0.0865,
      "f1": 0.25,
      "mae": 2.7721,
      "pairwiseAccuracy": 0.7548,
      "positives": 24,
      "prAuc": 0.4113,
      "precision": 0.5,
      "recall": 0.1667,
      "spearman": 0.6169
    },
    "selected": {
      "balancedAccuracy": 0.5756,
      "brier": 0.0872,
      "f1": 0.2581,
      "mae": 2.8723,
      "pairwiseAccuracy": 0.7392,
      "positives": 24,
      "prAuc": 0.4118,
      "precision": 0.5714,
      "recall": 0.1667,
      "spearman": 0.5532
    },
    "targetQuality": {
      "balancedAccuracy": 0.599,
      "brier": 0.0859,
      "f1": 0.3226,
      "mae": 2.924,
      "pairwiseAccuracy": 0.7237,
      "positives": 24,
      "prAuc": 0.4393,
      "precision": 0.7143,
      "recall": 0.2083,
      "spearman": 0.5177
    }
  },
  "modelVersion": "nested-opportunity-target-v3",
  "prAucLift": -0.0109,
  "productionModel": {
    "components": {
      "catchRate": {
        "baseline": {
          "beta": [
            0.57232371,
            -0.00531301,
            0.00466013,
            0.01407263
          ],
          "mean": [
            5.2427509,
            4.63960321,
            0.22622951
          ],
          "std": [
            0.32012618,
            0.92237235,
            0.41838943
          ]
        },
        "residual": {
          "beta": [
            0.0,
            0.0024753,
            -0.00666395,
            -0.00511415,
            0.00609259
          ],
          "mean": [
            0.1147541,
            0.45689826,
            -0.10869602,
            -0.24260984
          ],
          "std": [
            0.31872495,
            0.20404227,
            0.51981731,
            0.56162739
          ]
        }
      },
      "rushingPointsPerGame": {
        "baseline": {
          "beta": [
            0.13900726,
            0.03061712,
            -0.06773258,
            0.03375024
          ],
          "mean": [
            5.2427509,
            4.63960321,
            0.22622951
          ],
          "std": [
            0.32012618,
            0.92237235,
            0.41838943
          ]
        },
        "residual": {
          "beta": [
            -0.0,
            -0.03769349,
            0.02804269,
            0.00489295,
            0.00962198
          ],
          "mean": [
            0.1147541,
            0.45689826,
            -0.10869602,
            -0.24260984
          ],
          "std": [
            0.31872495,
            0.20404227,
            0.51981731,
            0.56162739
          ]
        }
      },
      "targetsPerGame": {
        "baseline": {
          "beta": [
            2.86411583,
            -0.43946602,
            -0.78637827,
            0.36042155
          ],
          "mean": [
            5.2427509,
            4.63960321,
            0.22622951
          ],
          "std": [
            0.32012618,
            0.92237235,
            0.41838943
          ]
        },
        "residual": {
          "beta": [
            -0.0,
            -0.20802365,
            0.51473098,
            0.02286495,
            0.14704547
          ],
          "mean": [
            0.1147541,
            0.45689826,
            -0.10869602,
            -0.24260984
          ],
          "std": [
            0.31872495,
            0.20404227,
            0.51981731,
            0.56162739
          ]
        }
      },
      "touchdownsPerTarget": {
        "baseline": {
          "beta": [
            0.03749149,
            -0.00304488,
            2.338e-05,
            0.00437197
          ],
          "mean": [
            5.2427509,
            4.63960321,
            0.22622951
          ],
          "std": [
            0.32012618,
            0.92237235,
            0.41838943
          ]
        },
        "residual": {
          "beta": [
            0.0,
            0.00456568,
            -0.00262571,
            -0.00088829,
            0.00409005
          ],
          "mean": [
            0.1147541,
            0.45689826,
            -0.10869602,
            -0.24260984
          ],
          "std": [
            0.31872495,
            0.20404227,
            0.51981731,
            0.56162739
          ]
        }
      },
      "yardsPerTarget": {
        "baseline": {
          "beta": [
            6.84845953,
            -0.00048545,
            -0.17833475,
            0.46953102
          ],
          "mean": [
            5.2427509,
            4.63960321,
            0.22622951
          ],
          "std": [
            0.32012618,
            0.92237235,
            0.41838943
          ]
        },
        "residual": {
          "beta": [
            -0.0,
            0.09509202,
            0.02704238,
            -0.07249085,
            0.24539837
          ],
          "mean": [
            0.1147541,
            0.45689826,
            -0.10869602,
            -0.24260984
          ],
          "std": [
            0.31872495,
            0.20404227,
            0.51981731,
            0.56162739
          ]
        }
      }
    },
    "lane": "opportunity",
    "marketFeatureOrder": [
      "logAdp",
      "logDraftPick",
      "directAdp"
    ],
    "opportunityFeatureOrder": [
      "topThreePath",
      "inverseDepthRank",
      "collegeOpportunityDirection",
      "breakoutDirection"
    ]
  },
  "rankLift": -0.0116,
  "researchMae": 2.872,
  "researchWr3Accuracy": 0.5756,
  "samples": 217,
  "segments": {
    "directAdp": {
      "maeImprovement": -0.022,
      "market": {
        "balancedAccuracy": 0.5809,
        "brier": 0.2013,
        "f1": 0.3,
        "mae": 3.1293,
        "pairwiseAccuracy": 0.6923,
        "positives": 16,
        "prAuc": 0.5037,
        "precision": 0.75,
        "recall": 0.1875,
        "spearman": 0.5909
      },
      "opportunity": {
        "balancedAccuracy": 0.5737,
        "brier": 0.1984,
        "f1": 0.3333,
        "mae": 3.2857,
        "pairwiseAccuracy": 0.6697,
        "positives": 16,
        "prAuc": 0.4818,
        "precision": 0.5,
        "recall": 0.25,
        "spearman": 0.5351
      },
      "opportunityMaeImprovement": -0.05,
      "opportunityRankLift": -0.0558,
      "rankLift": -0.0311,
      "samples": 55,
      "selected": {
        "balancedAccuracy": 0.5865,
        "brier": 0.1999,
        "f1": 0.3478,
        "mae": 3.1981,
        "pairwiseAccuracy": 0.6697,
        "positives": 16,
        "prAuc": 0.4953,
        "precision": 0.5714,
        "recall": 0.25,
        "spearman": 0.5598
      }
    },
    "proxyAdp": {
      "maeImprovement": -0.0059,
      "market": {
        "balancedAccuracy": 0.5,
        "brier": 0.0489,
        "f1": 0,
        "mae": 2.7454,
        "pairwiseAccuracy": 0.6649,
        "positives": 8,
        "prAuc": 0.3781,
        "precision": 0.0,
        "recall": 0.0,
        "spearman": 0.3011
      },
      "opportunity": {
        "balancedAccuracy": 0.5,
        "brier": 0.0485,
        "f1": 0,
        "mae": 2.5978,
        "pairwiseAccuracy": 0.6867,
        "positives": 8,
        "prAuc": 0.4011,
        "precision": 0.0,
        "recall": 0.0,
        "spearman": 0.4062
      },
      "opportunityMaeImprovement": 0.0538,
      "opportunityRankLift": 0.1051,
      "rankLift": -0.0194,
      "samples": 162,
      "selected": {
        "balancedAccuracy": 0.5,
        "brier": 0.0489,
        "f1": 0,
        "mae": 2.7616,
        "pairwiseAccuracy": 0.6534,
        "positives": 8,
        "prAuc": 0.1803,
        "precision": 0.0,
        "recall": 0.0,
        "spearman": 0.2817
      }
    }
  },
  "selectedAdjustment": {
    "efficiencyWeight": 0,
    "maxPercent": 0.08,
    "opportunityWeight": 1
  },
  "stableHoldouts": 0,
  "trainingSeasons": [
    2016,
    2017,
    2018
  ],
  "wr3AccuracyLift": 0.0157
} as const;
