export const FIRST_NAMES = [
  "Jay","Ty","Deon","Chris","Mike","Andre","Tony","Zay",
  "Jalen","Darius","Malik","Travis","Kareem","Marcus",
  "Trey","Lamar","Jordan","Bryce","Caleb","Justin",
  "Devon","Avery","Rashad","Xavier","Isaiah","Noah",
  "Cam","Aaron","CJ","Trevor","Desmond","Keon",
  "Nico","Stefon","AJ","Ja'Marr","DeVonta","Quentin",
  "Rome","Brock","Sam","Bo","Drake","Theo","Kendrick",
  "Mason","Dre","Antoine","Ray","Khalil","Zion",
  "Tariq","Javon","Mekhi","Emory","KJ","Tatum",
  "Donovan","Micah","Nasir","Omari","Caden","Preston",
  "Tobias","Kyler","Dallas","Kobe","Aidan","Joaquin",
  "Rico","Cedric","Damari","Eli","Jace","Wes",
  "Riley","Lance","Shane","Brandon","Colt","Hudson",
  "Chance","Marcellus","Tahj","Kylan","Julian","Corbin",
  "Dawson","Trent","Ashton","Kaden","Royce","Keenan",
  "Terrance","Jabari","Elijah","Maddox","Bryson","Cooper",
  "Miles","Logan","Carter","Sawyer","Bennett","Owen",
  "Emmett","Tanner","Kash","Troy","Dillon","Jeremiah"
];

export const LAST_NAMES = [
  "Smith","Johnson","Brown","Davis","Moore","Taylor",
  "Wilson","Martinez","Anderson","Thomas","Jackson",
  "White","Harris","Clark","Lewis","Robinson","Walker",
  "Young","Allen","King","Wright","Scott","Green",
  "Baker","Adams","Nelson","Hill","Campbell","Mitchell",
  "Carter","Roberts","Phillips","Evans","Turner",
  "Parker","Collins","Edwards","Stewart","Flores",
  "Morris","Reed","Cook","Morgan","Bell","Murphy",
  "Brooks","Bailey","Richardson","Ward","Cox","Howard",
  "Wardlow","Peterson","Gray","James","Watson","Barnes",
  "Ross","Henderson","Coleman","Jenkins","Perry","Powell",
  "Long","Patterson","Hughes","Washington","Simmons","Foster",
  "Butler","Gonzalez","Bryant","Alexander","Russell","Griffin",
  "Diaz","Hayes","Myers","Ford","Hamilton","Graham",
  "Sullivan","Wallace","Woods","Cole","West","Jordan",
  "Owens","Reynolds","Fisher","Ellis","Porter","Hunter",
  "Stephens","Payne","Bennett","Price","Sanders","Barnett",
  "Black","Daniels","Schultz","Mendoza","Cunningham","Hawkins",
  "Armstrong","Bishop","Goodwin","Knight","Arnold","Hudson"
];

export const SCHOOL_PREFIXES = [
  "Georgia",
  "Texas",
  "Coastal",
  "Appalachian",
  "Central",
  "Western",
  "Prairie View",
  "Eastern",
  "Northern",
  "Southern",
  "Midwest",
  "Atlantic",
  "Pacific",
  "Carolina",
  "Florida",
  "Alabama",
  "Virginia",
  "Indiana",
  "Colorado",
  "Utah",
  "Metro",
  "Gulf Coast",
  "Red River",
  "Blue Ridge",
  "Desert",
  "Frontier",
  "Heartland",
  "Great Lakes",
  "Bayou",
  "Highland",
  "Lowcountry",
  "Ozark",
  "Piedmont",
  "River City",
  "Sun Belt",
  "Blackstone",
  "Cumberland",
  "Dakota",
  "Magnolia",
  "Nevada",
  "Montana",
  "Kansas",
  "Tennessee",
  "Phoenix",
  "Cascade",
  "Sierra",
  "Golden Coast",
  "Plains",
  "Rocky Mountain"
];

export const SCHOOL_SUFFIXES = [
  "University",
  "College",
  "Tech",
  "State",
  "A&M",
  "A&T",
  "Institute",
  "Polytechnic",
  "Academy",
  "Union",
  "Christian",
  "Prep",
  "Normal",
  "Military Institute",
  "Arts & Sciences",
  "Technical College",
  "Agricultural College",
  "Maritime",
  "Teachers College",
  "State University"
];
