import { buildCanonicalPlayers } from "@/lib/fantasy/identity";
import type {
  InSeasonPlayerSnapshot,
  InSeasonTeamSnapshot,
  ProviderPlayerRecord,
  UsageWindowSnapshot,
} from "@/lib/fantasy/types";

const providerRecords: ProviderPlayerRecord[] = [
  {
    provider: "manual",
    providerPlayerId: "gibbs",
    fullName: "Jahmyr Gibbs",
    team: "DET",
    positions: ["RB"],
    age: 24,
    externalIds: { yahoo: "40059" },
  },
  {
    provider: "manual",
    providerPlayerId: "amon-ra",
    fullName: "Amon-Ra St. Brown",
    team: "DET",
    positions: ["WR"],
    age: 26,
    externalIds: { yahoo: "33495" },
  },
  {
    provider: "manual",
    providerPlayerId: "kittle",
    fullName: "George Kittle",
    team: "SF",
    positions: ["TE"],
    age: 33,
    externalIds: { yahoo: "29265" },
  },
  {
    provider: "fantasypros",
    providerPlayerId: "fp-bijan",
    fullName: "Bijan Robinson",
    team: "ATL",
    positions: ["RB"],
    age: 24,
    externalIds: { fantasyPros: "fp-bijan", sleeper: "4017", yahoo: "33186" },
  },
  {
    provider: "fantasypros",
    providerPlayerId: "fp-mhj",
    fullName: "Marvin Harrison Jr.",
    team: "ARI",
    positions: ["WR"],
    age: 24,
    externalIds: { fantasyPros: "fp-mhj", sleeper: "11699", yahoo: "37314" },
  },
  {
    provider: "fantasypros",
    providerPlayerId: "fp-bowers",
    fullName: "Brock Bowers",
    team: "LV",
    positions: ["TE"],
    age: 23,
    externalIds: { fantasyPros: "fp-bowers", sleeper: "11697", yahoo: "37318" },
  },
  {
    provider: "fantasypros",
    providerPlayerId: "fp-daniels",
    fullName: "Jayden Daniels",
    team: "WAS",
    positions: ["QB"],
    age: 25,
    externalIds: { fantasyPros: "fp-daniels", sleeper: "11566", yahoo: "37264" },
  },
  {
    provider: "fantasypros",
    providerPlayerId: "fp-brown",
    fullName: "Chase Brown",
    team: "CIN",
    positions: ["RB"],
    age: 26,
    externalIds: { fantasyPros: "fp-brown", sleeper: "8112", yahoo: "34429" },
  },
  {
    provider: "manual",
    providerPlayerId: "tyjae",
    fullName: "Tyjae Spears",
    team: "TEN",
    positions: ["RB"],
    age: 25,
    externalIds: { sleeper: "9223" },
  },
  {
    provider: "manual",
    providerPlayerId: "rome",
    fullName: "Rome Odunze",
    team: "CHI",
    positions: ["WR"],
    age: 24,
    externalIds: { sleeper: "11804" },
  },
];

function usage(
  input: UsageWindowSnapshot,
): UsageWindowSnapshot {
  return input;
}

const players = buildCanonicalPlayers(providerRecords);

const playerByName = new Map(players.map((player) => [player.fullName, player] as const));

function snapshot(
  name: string,
  input: Omit<InSeasonPlayerSnapshot, "player">,
) {
  const player = playerByName.get(name);
  if (!player) {
    throw new Error(`Missing in-season fixture player: ${name}`);
  }

  return {
    player,
    ...input,
  } satisfies InSeasonPlayerSnapshot;
}

export const inSeasonFixturePlayers: InSeasonPlayerSnapshot[] = [
  snapshot("Jahmyr Gibbs", {
    availability: "my-roster",
    rosterTeamId: "me",
    weeklyProjection: { p10: 13, p50: 18.6, p90: 28.4 },
    rosProjection: { p10: 182, p50: 235, p90: 302 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.58,
      routeParticipation: 0.47,
      carriesPerGame: 14.2,
      targetsPerGame: 5.6,
      targetShare: 0.12,
      airYardsShare: 0.02,
      redZoneTouchesPerGame: 4.4,
      fantasyPointsPerGame: 18.3,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.61,
      routeParticipation: 0.49,
      carriesPerGame: 15.5,
      targetsPerGame: 6.2,
      targetShare: 0.13,
      airYardsShare: 0.02,
      redZoneTouchesPerGame: 4.8,
      fantasyPointsPerGame: 19.6,
    }),
    marketTrend: "steady",
    marketTrendCount: 0,
  }),
  snapshot("Amon-Ra St. Brown", {
    availability: "my-roster",
    rosterTeamId: "me",
    weeklyProjection: { p10: 14.1, p50: 19.8, p90: 29.3 },
    rosProjection: { p10: 196, p50: 247, p90: 318 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.88,
      routeParticipation: 0.93,
      carriesPerGame: 0.6,
      targetsPerGame: 10.8,
      targetShare: 0.29,
      airYardsShare: 0.28,
      redZoneTouchesPerGame: 2.8,
      fantasyPointsPerGame: 20.4,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.89,
      routeParticipation: 0.95,
      carriesPerGame: 0.5,
      targetsPerGame: 11.2,
      targetShare: 0.3,
      airYardsShare: 0.29,
      redZoneTouchesPerGame: 3,
      fantasyPointsPerGame: 21.1,
    }),
    marketTrend: "steady",
    marketTrendCount: 0,
  }),
  snapshot("George Kittle", {
    availability: "my-roster",
    rosterTeamId: "me",
    weeklyProjection: { p10: 8.2, p50: 12.8, p90: 20.1 },
    rosProjection: { p10: 112, p50: 156, p90: 219 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.76,
      routeParticipation: 0.73,
      carriesPerGame: 0,
      targetsPerGame: 6.4,
      targetShare: 0.18,
      airYardsShare: 0.17,
      redZoneTouchesPerGame: 1.5,
      fantasyPointsPerGame: 12.1,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.73,
      routeParticipation: 0.69,
      carriesPerGame: 0,
      targetsPerGame: 5.5,
      targetShare: 0.16,
      airYardsShare: 0.15,
      redZoneTouchesPerGame: 1.2,
      fantasyPointsPerGame: 10.7,
    }),
    marketTrend: "drop",
    marketTrendCount: 180,
  }),
  snapshot("Chase Brown", {
    availability: "my-roster",
    rosterTeamId: "me",
    weeklyProjection: { p10: 6.8, p50: 10.4, p90: 17.6 },
    rosProjection: { p10: 108, p50: 143, p90: 214 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.52,
      routeParticipation: 0.46,
      carriesPerGame: 12.7,
      targetsPerGame: 4.1,
      targetShare: 0.09,
      airYardsShare: 0.04,
      redZoneTouchesPerGame: 2.3,
      fantasyPointsPerGame: 12.4,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.47,
      routeParticipation: 0.39,
      carriesPerGame: 10.1,
      targetsPerGame: 2.9,
      targetShare: 0.06,
      airYardsShare: 0.03,
      redZoneTouchesPerGame: 1.5,
      fantasyPointsPerGame: 8.9,
    }),
    marketTrend: "add",
    marketTrendCount: 920,
  }),
  snapshot("Marvin Harrison Jr.", {
    availability: "trade-target",
    rosterTeamId: "team-7",
    weeklyProjection: { p10: 10.2, p50: 16.3, p90: 25.8 },
    rosProjection: { p10: 168, p50: 219, p90: 296 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.78,
      routeParticipation: 0.86,
      carriesPerGame: 0.3,
      targetsPerGame: 7.2,
      targetShare: 0.2,
      airYardsShare: 0.29,
      redZoneTouchesPerGame: 1.6,
      fantasyPointsPerGame: 13.8,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.87,
      routeParticipation: 0.93,
      carriesPerGame: 0.5,
      targetsPerGame: 10.1,
      targetShare: 0.28,
      airYardsShare: 0.38,
      redZoneTouchesPerGame: 2.4,
      fantasyPointsPerGame: 18.9,
    }),
    marketTrend: "add",
    marketTrendCount: 780,
  }),
  snapshot("Brock Bowers", {
    availability: "trade-target",
    rosterTeamId: "team-3",
    weeklyProjection: { p10: 9.8, p50: 14.6, p90: 23.2 },
    rosProjection: { p10: 149, p50: 198, p90: 274 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.82,
      routeParticipation: 0.87,
      carriesPerGame: 0,
      targetsPerGame: 8.3,
      targetShare: 0.23,
      airYardsShare: 0.21,
      redZoneTouchesPerGame: 1.8,
      fantasyPointsPerGame: 15.1,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.83,
      routeParticipation: 0.88,
      carriesPerGame: 0,
      targetsPerGame: 8.6,
      targetShare: 0.24,
      airYardsShare: 0.22,
      redZoneTouchesPerGame: 1.9,
      fantasyPointsPerGame: 15.5,
    }),
    marketTrend: "steady",
    marketTrendCount: 0,
  }),
  snapshot("Jayden Daniels", {
    availability: "trade-target",
    rosterTeamId: "team-9",
    weeklyProjection: { p10: 16.5, p50: 22.4, p90: 33.6 },
    rosProjection: { p10: 205, p50: 262, p90: 341 },
    baselineUsage: usage({
      games: 5,
      snapShare: 1,
      routeParticipation: 0,
      carriesPerGame: 9.1,
      targetsPerGame: 0,
      targetShare: 0,
      airYardsShare: 0,
      redZoneTouchesPerGame: 3.4,
      fantasyPointsPerGame: 21.7,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 1,
      routeParticipation: 0,
      carriesPerGame: 10.2,
      targetsPerGame: 0,
      targetShare: 0,
      airYardsShare: 0,
      redZoneTouchesPerGame: 4,
      fantasyPointsPerGame: 24.6,
    }),
    marketTrend: "add",
    marketTrendCount: 520,
    liveStats: {
      gameStatus: "live",
      updatedAt: "2026-08-12T20:14:00-04:00",
      rushingAttempts: 6,
      targets: 0,
      receptions: 0,
      rushingYards: 42,
      receivingYards: 0,
      touchdowns: 1,
    },
  }),
  snapshot("Bijan Robinson", {
    availability: "trade-target",
    rosterTeamId: "team-2",
    weeklyProjection: { p10: 13.1, p50: 18.7, p90: 27.5 },
    rosProjection: { p10: 186, p50: 232, p90: 299 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.63,
      routeParticipation: 0.52,
      carriesPerGame: 16.4,
      targetsPerGame: 4.6,
      targetShare: 0.12,
      airYardsShare: 0.04,
      redZoneTouchesPerGame: 4.1,
      fantasyPointsPerGame: 18,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.64,
      routeParticipation: 0.53,
      carriesPerGame: 16.1,
      targetsPerGame: 4.2,
      targetShare: 0.11,
      airYardsShare: 0.04,
      redZoneTouchesPerGame: 4.2,
      fantasyPointsPerGame: 17.7,
    }),
    marketTrend: "steady",
    marketTrendCount: 0,
  }),
  snapshot("Tyjae Spears", {
    availability: "free-agent",
    rosterTeamId: null,
    weeklyProjection: { p10: 5.1, p50: 8.9, p90: 17.3 },
    rosProjection: { p10: 94, p50: 131, p90: 205 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.31,
      routeParticipation: 0.27,
      carriesPerGame: 5.8,
      targetsPerGame: 2.3,
      targetShare: 0.06,
      airYardsShare: 0.02,
      redZoneTouchesPerGame: 0.6,
      fantasyPointsPerGame: 6.4,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.49,
      routeParticipation: 0.43,
      carriesPerGame: 10.9,
      targetsPerGame: 4.4,
      targetShare: 0.11,
      airYardsShare: 0.03,
      redZoneTouchesPerGame: 1.9,
      fantasyPointsPerGame: 12.8,
    }),
    marketTrend: "steady",
    marketTrendCount: 90,
  }),
  snapshot("Rome Odunze", {
    availability: "free-agent",
    rosterTeamId: null,
    weeklyProjection: { p10: 4.8, p50: 8.2, p90: 15.1 },
    rosProjection: { p10: 86, p50: 124, p90: 190 },
    baselineUsage: usage({
      games: 5,
      snapShare: 0.42,
      routeParticipation: 0.56,
      carriesPerGame: 0,
      targetsPerGame: 3.6,
      targetShare: 0.1,
      airYardsShare: 0.12,
      redZoneTouchesPerGame: 0.7,
      fantasyPointsPerGame: 7,
    }),
    recentUsage: usage({
      games: 2,
      snapShare: 0.44,
      routeParticipation: 0.58,
      carriesPerGame: 0,
      targetsPerGame: 3.8,
      targetShare: 0.1,
      airYardsShare: 0.13,
      redZoneTouchesPerGame: 0.6,
      fantasyPointsPerGame: 7.2,
    }),
    marketTrend: "add",
    marketTrendCount: 640,
  }),
];

export const inSeasonFixtureMyTeam: InSeasonTeamSnapshot = {
  teamId: "me",
  name: "H-Town Heroes",
  playerIds: inSeasonFixturePlayers
    .filter((player) => player.rosterTeamId === "me")
    .map((player) => player.player.id),
};

export const inSeasonFixtureLeagueTeams: InSeasonTeamSnapshot[] = [
  inSeasonFixtureMyTeam,
  {
    teamId: "team-2",
    name: "Team 2",
    playerIds: inSeasonFixturePlayers
      .filter((player) => player.rosterTeamId === "team-2")
      .map((player) => player.player.id),
  },
  {
    teamId: "team-3",
    name: "Team 3",
    playerIds: inSeasonFixturePlayers
      .filter((player) => player.rosterTeamId === "team-3")
      .map((player) => player.player.id),
  },
  {
    teamId: "team-7",
    name: "Team 7",
    playerIds: inSeasonFixturePlayers
      .filter((player) => player.rosterTeamId === "team-7")
      .map((player) => player.player.id),
  },
  {
    teamId: "team-9",
    name: "Team 9",
    playerIds: inSeasonFixturePlayers
      .filter((player) => player.rosterTeamId === "team-9")
      .map((player) => player.player.id),
  },
];
