#!/usr/bin/env python3
"""Walk-forward validation for stable usage, TD regression, and bounded age inputs."""

import argparse
import csv
import json
from pathlib import Path
import numpy as np


def num(row, key):
    try:
        return float(row.get(key) or 0)
    except ValueError:
        return 0.0


def load(path):
    with path.open(encoding="utf-8") as handle:
        return {row["player_id"]: row for row in csv.DictReader(handle) if row.get("position") in {"RB", "WR", "TE"}}


def age_map(path, season):
    output = {}
    with path.open(encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            birth = row.get("birth_date") or ""
            if birth[:4].isdigit() and row.get("gsis_id"):
                output[row["gsis_id"]] = season - int(birth[:4])
    return output


def opportunity(row, position):
    if position in {"WR", "TE"}:
        return 1.5 * num(row, "target_share") + 0.7 * num(row, "air_yards_share")
    return num(row, "carries") * .52 + num(row, "targets") * 1.35 + num(row, "receptions") * .5 + num(row, "target_share") * 80


def age_risk(position, age):
    if position == "RB": return max(0, min(8, (age - 24) * 2))
    if position == "WR": return max(0, min(7, (age - 28) * 2))
    return 0


def rows_for(prior, current, ages, season):
    records = []
    by_position = {position: [] for position in ["RB", "WR", "TE"]}
    for player_id, row in prior.items():
        if player_id in current and num(row, "games") >= 8 and num(current[player_id], "games") >= 8:
            by_position[row["position"]].append(opportunity(row, row["position"]))
    moments = {position: (np.mean(values), np.std(values)) for position, values in by_position.items() if values}
    for player_id, row in prior.items():
        next_row = current.get(player_id)
        if not next_row or num(row, "games") < 8 or num(next_row, "games") < 8: continue
        position = row["position"]
        mean, std = moments.get(position, (0, 0))
        z = (opportunity(row, position) - mean) / std if std else 0
        prior_ppg = num(row, "fantasy_points_ppr") / max(1, num(row, "games"))
        next_ppg = num(next_row, "fantasy_points_ppr") / max(1, num(next_row, "games"))
        touches = num(row, "carries") + num(row, "targets")
        td_rate = (num(row, "rushing_tds") + num(row, "receiving_tds")) / max(1, touches)
        age = ages.get(player_id, 0) - (2026 - season)
        records.append((position, prior_ppg, z, td_rate, age_risk(position, age), next_ppg))
    return records


def fit(train, advanced):
    x = [[1, row[1]] + ([row[2], row[3], row[4]] if advanced else []) for row in train]
    y = [row[5] for row in train]
    return np.linalg.lstsq(np.array(x), np.array(y), rcond=None)[0]


def predict(beta, row, advanced):
    x = [1, row[1]] + ([row[2], row[3], row[4]] if advanced else [])
    return float(np.dot(beta, x))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--players", type=Path, required=True)
    parser.add_argument("--season", action="append", nargs=2, metavar=("YEAR", "CSV"), required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    seasons = {int(year): load(Path(path)) for year, path in args.season}
    ages = age_map(args.players, 2026)
    train = []
    for year in [2021, 2022, 2023]: train.extend(rows_for(seasons[year], seasons[year + 1], ages, year))
    test = rows_for(seasons[2024], seasons[2025], ages, 2024)
    reports = []
    for position in ["RB", "WR", "TE"]:
        tr = [row for row in train if row[0] == position]
        te = [row for row in test if row[0] == position]
        base_beta, advanced_beta = fit(tr, False), fit(tr, True)
        baseline_mae = np.mean([abs(predict(base_beta, row, False) - row[5]) for row in te])
        advanced_mae = np.mean([abs(predict(advanced_beta, row, True) - row[5]) for row in te])
        improvement = (baseline_mae - advanced_mae) / baseline_mae if baseline_mae else 0
        reports.append({"position": position, "trainSamples": len(tr), "holdoutSamples": len(te), "holdoutSeason": 2025, "baselineMae": round(baseline_mae, 3), "advancedMae": round(advanced_mae, 3), "maeImprovement": round(improvement, 4), "activationEligible": bool(len(te) >= 30 and improvement >= .03)})
    rendered = json.dumps({"generatedAt": "2026-08-13", "trainSeasons": [2022, 2023, 2024], "holdoutSeason": 2025, "reports": reports}, indent=2)
    args.output.write_text("// Generated by scripts/build_advanced_usage_validation.py.\nexport const advancedUsageValidation = " + rendered + " as const;\n", encoding="utf-8")


if __name__ == "__main__": main()
