#!/usr/bin/env python3
import argparse, csv, json
from collections import defaultdict
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--season", type=int, required=True)
parser.add_argument("--weekly", type=Path, required=True)
parser.add_argument("--output", type=Path, required=True)
args = parser.parse_args()
counts = defaultdict(lambda: {"passing300Games": 0, "rushing100Games": 0, "receiving100Games": 0})
with args.weekly.open(encoding="utf-8") as handle:
    for row in csv.DictReader(handle):
        player_id = row.get("player_id")
        if not player_id: continue
        def number(key):
            try: return float(row.get(key) or 0)
            except ValueError: return 0
        if number("passing_yards") >= 300: counts[player_id]["passing300Games"] += 1
        if number("rushing_yards") >= 100: counts[player_id]["rushing100Games"] += 1
        if number("receiving_yards") >= 100: counts[player_id]["receiving100Games"] += 1
compact = {key: value for key, value in counts.items() if sum(value.values()) > 0}
rendered = json.dumps(compact, indent=2, sort_keys=True)
args.output.write_text(f"// Generated by scripts/build_nfl_milestone_snapshot.py.\nexport const nflMilestones{args.season} = {rendered} as const;\n", encoding="utf-8")
